baseURL = "/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Duncan Gates Personal Website"
    author = "Duncan Gates"
    description = "Duncan Gates's personal website"
    copyright = "Duncan Gates"

    [params.theme]
        allowToggle = true
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        altTheme = "pinkish"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Duncan Gates, B.S."
		tagline = "Data Scientist"
		location = "Corvallis, OR"
        photo = "profile.jpg"

    # Section for links to social websites ---------------------------------
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/duncan-gates/"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/itsthesnake"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/gates_duncan"
            title = "Twitter"
		    [[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "http://bit.ly/goo-schlr-duncangates"
            title = "Google Scholar"
        [[params.social.list]]
            class = "fa"
            icon = "fa-file"
            url = "/cv/cv.html"
            title = "Curriculum Vitae"

    #Specify what is showin in the Accordion  ---------------------------------
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Hi! I'm Duncan Gates**, a recent graduate from Oregon State University. I specialize in data analytics, statistics, and research over a variety of fields. This website is just getting organized so excuse the messiness."

    # Experience section  ------------------------------------------------------
    [params.experience]
        title = "Resume"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            #position = "Data Scientst, Co-Founder"
            #dates = "2019 - *Present*"
            #company = "Paradigm Data Group"
            #link = "https://www.paradigmdata.io/"
            #details = "Our company provides data science trainings and solutions to companies, schools, teams, and individuals."


    # Education section --------------------------------------------------------
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "B.S. in Mathematical Economics, Actuarial Science, and Political Science"
            college = "Oregon State University, Corvallis"
            dates = "2017 - 2020"
            thesis_title = "The Relationship Between Income Taxation, Social Benefits, and Wealth Inequality in OECD Countries: Exploring the Factors Contributing to Unequal Household Wealth"
            thesis_link = "https://www.google.com"

    # Publication section  -----------------------------------------------------
    [params.publication]
        title = "Writing"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Tutorials", "Journal Articles", "Book Chapters", "Posters & Abstracts"]

        [[params.publication.list]]
            title = "Making Your Own Website with R Markdown"
            authors = "Duncan Gates"
            date = "2020"
            journal = ""
            link = "http://www.youtube.com"
            type = "Tutorials"

    # Project section  --------------------------------------------------------
    [params.project]
        title = "Data Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Tinder Romance Algorithm"
            url = "https://leanpub.com/showingyourwork/"
            description = "Propietary analytics to determine optimal dating app strategies. Currently has only been conducted with self-collected data on Tinder."

        [[params.project.list]]
            title = "Wealth and Happiness"
            url = "https://www.diabetestechnology.org/seg/"
            description = "Exploring the relationship of wealth and happiness by looking for key points in the marginal effect of happiness on wealth."

        [[params.project.list]]
            title = "Algorithmic Spotify Recommendations"
            url = "https://www.tidyverse.tips/"
            description = "A project designed to rethink the way we listen to music, using markov chains to analyze similar music tastes by key signatures and other novel unanalyzed similarities between music tastes by technology companies."

    # Skill section --------------------------------------------------------

    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Economic Theory and Applied Statistics"
            skillrating = 75
        [[params.skill.list]]
            skill = "R Programming & Data visualization"
            skillrating = 85
        [[params.skill.list]]
            skill = "Teamwork & Communication"
            skillrating = 80
        [[params.skill.list]]
            skill = "Website Design (Very New Skill)"
            skillrating = 30

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
		    hobby = "Basketball"
        [[params.hobby.list]]
		    hobby = "Piano"
        [[params.hobby.list]]
		    hobby = "Running"
