baseURL = "https://www.duncangates.me"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Duncan Gates dot io"
    author = "Duncan Gates"
    description = "Duncan Gates's personal website"
    copyright = "Duncan Gates"

    [params.theme]
        allowToggle = true
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "pinkish"
        altTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Duncan Gates, BS"
		tagline = "Data Scientist"
		location = "Corvallis, OR"
        photo = "profile.jpg"

    # Section for links to social websites ---------------------------------
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/duncan-gates/"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/itsthesnake"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/gates_duncan"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "http://bit.ly/goo-schlr-duncangates"
            title = "Google Scholar"

    #Specify what is showin in the Accordion  ---------------------------------
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Hi! I'm Duncan Gates**, a recent graduate from Oregon State University. I specialize in data analytics, statistics, and research over a variety of fields. This website is just getting organized so excuse the messiness."

    # Experience section  ------------------------------------------------------
    [params.experience]
        title = "Experience"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Data Scientst, Co-Founder"
            dates = "2019 - *Present*"
            company = "Paradigm Data Group"
            link = "https://www.paradigmdata.io/"
            details = "Our company provides data science trainings and solutions to companies, schools, teams, and individuals."
        [[params.experience.list]]
            position = "Author/Contributor"
            dates = "2016 - *Present*"
            company = "Storybench"
            link = "[Data Journalism in R](http://www.storybench.org/category/data-journalism-in-r/)"
            details = "I've been a contributing author since 2016, and I write R/RStudio tutorials and how-tos for data journalists."
        [[params.experience.list]]
            position = "Computational & Data Science Research Specialist III"
            dates = "2017 - 2018"
            link = "https://www.ucsf.edu/research"
            company = "University of California, San Francisco"
            details = "I was responsible for analyzing existing software, scientific code, data science/analytics code/algorithms and applied complex programming practices. I also worked with domain scientists where applicable to perform these responsibilities and uses domain science knowledge where relevant."
        [[params.experience.list]]
            position = "Researcher Associate"
            dates = "2015 - 2017"
            company = "NCIRE - The Veterans Health Research Institute"
            link = "https://www.ncire.org/"
            details = "As the Research Associate, I was responsible for the data management of all clinical research volunteers (physicians and clinical pharmacists) and subjects (trial participants) to ensure veterans were screened or diagnosed with chronic kidney disease."
        [[params.experience.list]]
            position = "Researcher Scientist"
            dates = "2011 - 2014"
            company = "CNAP - The Center for Nutrition and Activity Promotion"
            link = "https://www.csuchico.edu/chc/"
            details = "As the Research Scientist, I was responsible for the selection and application of appropriate evaluation methods, techniques, practices, and procedures. I also oversaw the work of four interns by establishing priorities, coordinating activities, and resolving related work problems."


    # Education section --------------------------------------------------------
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "B.S. in Mathematical Economics, Actuarial Science, and Political Science"
            college = "Oregon State University, Corvallis"
            dates = "2017 - 2020"
            thesis_title = "Validating laboratory defined chronic kidney disease in the electronic health record for patients in primary care"
            thesis_link = "https://bmcnephrol.biomedcentral.com/articles/10.1186/s12882-018-1156-2"

    # Publication section  -----------------------------------------------------
    [params.publication]
        title = "Writing"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Tutorials", "Journal Articles", "Book Chapters", "Posters & Abstracts"]

        [[params.publication.list]]
            title = "Data Journalism in R."
            authors = "M Frigaard & Aleszu Bajak."
            date = "2019"
            journal = "Storybench (Northeastern University's School of Journalism)"
            link = "http://www.storybench.org/category/data-journalism-in-r/"
            type = "Tutorials"

        [[params.publication.list]]
            title = "Validating laboratory defined chronic kidney disease in the electronic health record for patients in primary care."
            authors = "M Frigaard, A Rubinsky, L Lowell, A Malkina, L Karliner, M Kohn, CA Peralta."
            date = "2019"
            journal = "BMC nephrology. 2019 Jan;20(3):3."
            link = "https://www.ncbi.nlm.nih.gov/pubmed/28399844"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Implementation of a pragmatic randomized trial of screening for chronic kidney disease to improve care among non-diabetic hypertensive veterans."
            authors = "CA Peralta, M Frigaard, AD Rubinsky, L Rolon, L Lo, S Voora, K Seal, D Tuot, S Chao, K Lui, P Chiao, N Powe, M Shlipak."
            date = "2017"
            journal = "BMC Nephrology. 2017 Apr 12;18(1):132."
            link = "https://www.ncbi.nlm.nih.gov/pubmed/28399844"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Genetic Testing and Privacy Issues"
            authors = "M Frigaard (published with K. Lee Lerner)"
            date = "2015"
            journal = "Worldmark Global Health and Medicine Issues, 1st Edition"
            link = "https://www.dropbox.com/s/kc4sldkxe178594/2016-genetic-testing-priv-issues-worldmark-global-health-and-medicine-issues-1st-edition.pdf?dl=0"
            type = "Book Chapters"

        [[params.publication.list]]
            title = "Noncommunicable Diseases (Lifestyle Diseases)"
            authors = "M Frigaard (published with K. Lee Lerner)"
            date = "2015"
            journal = "Worldmark Global Health and Medicine Issues, 1st Edition"
            link = "https://www.dropbox.com/s/epfop5cfyk9xdly/2016-noncommunicable-diseases-lifestyle-diseases-worldmark-global-health-and-medicine-issues-1st-edition.pdf?dl=0"
            type = "Book Chapters"

        [[params.publication.list]]
            title = "Pharmaceutical Research, Testing, and Access, Sidebar: Pharmaceutical Supply to Developing Nations"
            authors = "M Frigaard (published with K. Lee Lerner)"
            date = "2015"
            journal = "Worldmark Global Health and Medicine Issues, 1st Edition"
            link = "https://www.dropbox.com/s/twxn4rgdl8a42j5/2016-pharm-research-test-access-worldmark-global-health-and-medicine-issues-1st-edition.pdf?dl=0"
            type = "Book Chapters"

        [[params.publication.list]]
            title = "Vaccines, Sidebar: Experimental use in Ebola Outbreak"
            authors = "M Frigaard (published with K. Lee Lerner)"
            date = "2015"
            journal = "Worldmark Global Health and Medicine Issues, 1st Edition"
            link = "https://www.dropbox.com/s/tw0lorb5lp0bqva/2016-vaccines-worldmark-global-health-and-medicine-issues-1st-edition.pdf?dl=0"
            type = "Book Chapters"

        [[params.publication.list]]
            title = "Vaccine Preventable Diseases, Sidebar: MMR fraud and anti-vaccine movements"
            authors = "M Frigaard (published with K. Lee Lerner)"
            date = "2015"
            journal = "Worldmark Global Health and Medicine Issues, 1st Edition"
            link = "https://www.dropbox.com/s/14qhjmpc9o2t8na/2016-vaccine-prev-diseases-worldmark-global-health-and-medicine-issues-1st-edition.pdf?dl=0"
            type = "Book Chapters"

        [[params.publication.list]]
            title = "Identifying Red Flags: Using Anthropometry Measures to Screen for Elevated Blood Pressure Risk in Children"
            authors = "M Frigaard, K Goto, C Wolff, S Bianco-Simeral, T Fahey"
            date = "2013"
            journal = "Childhood Obesity and Nutrition. January 14, 2013"
            link = "https://journals.sagepub.com/doi/10.1177/1941406412470719"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "The Associations Between Ckd Diagnosis And Guideline-Driven Care"
            authors = "MJ Frigaard, L Karliner, C Peralta"
            date = "2018"
            journal = "American Journal Of Kidney Diseases 71 (4), 539-539"
            link = "https://www.ajkd.org/article/S0272-6386(18)30232-4/fulltext"
            type = "Posters & Abstracts"

        [[params.publication.list]]
            title = "Comparison Of Historical Lab-Ckd And Clinician Chart Review."
            authors = "M Frigaard, C Peralta, L Karliner"
            date = "2018"
            journal = "American Journal Of Kidney Diseases 71 (4), 539-539"
            link = "https://www.ajkd.org/article/S0272-6386(18)30231-2/fulltext"
            type = "Posters & Abstracts"

    # Project section  --------------------------------------------------------
    [params.project]
        title = "Data Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Tinder Romance Algorithm"
            url = "https://leanpub.com/showingyourwork/"
            description = "Propietary analytics to determine optimal dating app strategies. Currently has only been conducted with self-collected data on Tinder."

        [[params.project.list]]
            title = "Wealth and Happiness"
            url = "https://www.diabetestechnology.org/seg/"
            description = "Exploring the relationship of wealth and happiness by looking for key points in the marginal effect of happiness on wealth."

        [[params.project.list]]
            title = "Algorithmic Spotify Recommendations"
            url = "https://www.tidyverse.tips/"
            description = "A project designed to rethink the way we listen to music, using markov chains to analyze similar music tastes by key signatures and other novel unanalyzed similarities between music tastes by technology companies."

    # Skill section --------------------------------------------------------

    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Economic Theory and Applied Statistics"
            skillrating = 75
        [[params.skill.list]]
            skill = "R Programming & Data visualization"
            skillrating = 85
        [[params.skill.list]]
            skill = "Teamwork & Communication"
            skillrating = 80
        [[params.skill.list]]
            skill = "Website Design (Very New Skill)"
            skillrating = 30

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
		    hobby = "Basketball"
        [[params.hobby.list]]
		    hobby = "Piano"
        [[params.hobby.list]]
		    hobby = "Running"
